name: c2kd
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.6.0=h6a678d5_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - blas=1.0=mkl
  - brotlicffi=1.0.9.2=py311h6a678d5_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2025.10.5=py311h06a4308_0
  - cffi=1.17.1=py311h1fdaa30_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - comm=0.2.3=pyhe01879c_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cuda-version=12.9=3
  - dav1d=1.2.1=h5eee18b_0
  - debugpy=1.8.17=py311hc665b79_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - ffmpeg=4.2.2=h20bf706_0
  - filelock=3.17.0=py311h06a4308_0
  - fontconfig=2.15.0=h2c49b7f_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - giflib=5.2.2=h5eee18b_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py311h5eee18b_0
  - gnutls=3.6.15=he1e5248_0
  - graphite2=1.3.14=h295c915_1
  - harfbuzz=10.2.0=hdfddeaa_1
  - icu=73.1=h6a678d5_0
  - idna=3.7=py311h06a4308_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2025.0.0=h06a4308_1171
  - ipykernel=6.30.1=pyh82676e8_0
  - ipython=9.6.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=py311h06a4308_0
  - jpeg=9f=h5ce9db8_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - krb5=1.21.3=h723845a_4
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libavif=1.1.1=h5eee18b_0
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.14.1.1=4
  - libcurand=10.3.10.19=0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h767d61c_6
  - libgcc-ng=15.2.0=h69a702a_6
  - libglib=2.84.2=h37c7471_0
  - libgomp=15.2.0=h767d61c_6
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libkrb5=1.21.3=h520c7b4_4
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libopus=1.3.1=h5eee18b_1
  - libpng=1.6.39=h5eee18b_0
  - libsodium=1.0.20=h4ab18f5_0
  - libstdcxx=15.2.0=h8f9b012_6
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.20.0=ha30cf84_0
  - libtiff=4.7.0=hde9077f_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.3.2=h9f374a3_1
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.8=hfdd30dd_0
  - libzlib=1.3.1=hb25bd0a_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lmdb=0.9.31=hd590300_1
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py311h5eee18b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mkl=2025.0.0=hacee8c2_941
  - mkl-service=2.5.2=py311hacdc0fc_0
  - mkl_fft=1.3.11=py311hacdc0fc_1
  - mkl_random=1.2.8=py311h2fd27a0_1
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py311h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.5=py311h06a4308_0
  - numpy=1.26.4=py311h64c44e4_1
  - numpy-base=1.26.4=py311he1678cf_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=h0d4d230_1
  - openssl=3.5.4=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py311hb1c3d2d_0
  - pip=25.2=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - platformdirs=4.4.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.0=py311h49ec1c0_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.23=py311h06a4308_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.13=h1a3bd86_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.11=2_cp311
  - pytorch-cuda=11.8=h7e8668a_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py311h5eee18b_0
  - pyzmq=27.1.0=py311h2315fbb_0
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=py311h06a4308_0
  - setuptools=78.1.1=py311h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sympy=1.14.0=py311h06a4308_0
  - tbb=2022.0.0=hdb19cb5_0
  - tbb-devel=2022.0.0=hdb19cb5_0
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.2=py311h49ec1c0_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - urllib3=2.5.0=py311h06a4308_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py311h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h387f397_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - annotated-types==0.7.0
      - audioread==3.0.1
      - cachetools==6.2.2
      - click==8.3.0
      - cmake==3.25.0
      - contourpy==1.3.3
      - cycler==0.12.1
      - decorator==4.4.2
      - fonttools==4.60.1
      - geomloss==0.2.6
      - git-filter-repo==2.47.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-api-core==2.28.1
      - google-api-python-client==2.187.0
      - google-auth==2.41.1
      - google-auth-httplib2==0.2.1
      - google-auth-oauthlib==1.2.3
      - googleapis-common-protos==1.72.0
      - httplib2==0.31.0
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - librosa==0.11.0
      - lit==15.0.7
      - llvmlite==0.45.1
      - matplotlib==3.10.7
      - moviepy==1.0.3
      - msgpack==1.1.2
      - numba==0.62.1
      - oauthlib==3.3.1
      - opencv-python==4.7.0.72
      - pandas==2.3.3
      - pooch==1.8.2
      - pot==0.9.6.post1
      - proglog==0.1.12
      - proto-plus==1.26.1
      - protobuf==6.33.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pyparsing==3.2.5
      - pytz==2025.2
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - scikit-learn==1.7.2
      - scipy==1.16.2
      - sentry-sdk==2.42.1
      - smmap==5.0.2
      - soundfile==0.13.1
      - soxr==1.0.0
      - threadpoolctl==3.6.0
      # - torch==2.0.1+cu118
      # - torchaudio==2.0.2+cu118
      # - torchvision==0.15.2+cu118
      - tqdm==4.67.1
      - triton==2.0.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - uritemplate==4.2.0
      - wandb==0.22.2
prefix: /home/anaconda3/envs/c2kd
