name: c2kd
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - numpy=1.24.2
  - pandas=1.5.3
  - scipy=1.10.1
  - scikit-learn
  - bottleneck
  - pytorch=2.0.0
  - torchvision=0.15.1
  - torchaudio=2.0.1
  - pytorch-cuda=11.8
  - cudnn
  - matplotlib
  - seaborn
  - jupyter
  - ipykernel
  - pillow=9.2.0
  - cython=0.29.35
  - cmake=3.25.0
  - lit=15.0.7
  - h5py=3.8.0
  - imageio=2.27.0
  - opencv=4.7.0
  - openpyxl
  - pyyaml=6.0
  - tqdm
  - requests
  - regex
  - numba=0.57.1
  - llvmlite=0.40.1
  - shapely=2.0.1
  - scikit-image=0.20.0
  - joblib
  - jinja2
  - packaging
  - psutil
  - typing_extensions
  - qtpy
  - qdarkstyle
  - pip:
      - absl-py==1.4.0
      - addict==2.4.0
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - anyio==3.7.0
      - appdirs==1.4.4
      - argcomplete==3.1.1
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - array-record==0.4.0
      - arrow==1.2.3
      - asttokens==2.2.1
      - astunparse==1.6.3
      - async-timeout==4.0.2
      - attrs==23.1.0
      - audioread==3.0.0
      - backcall==0.2.0
      - beartype==0.14.1
      - beautifulsoup4==4.12.0
      - bleach==6.0.0
      - blosc2==2.0.0
      - boto==2.49.0
      - braceexpand==0.1.7
      - brotlipy==0.7.0
      - cachetools==5.3.0
      - charset-normalizer==2.1.1
      - click==8.1.3
      - cloudpickle==2.2.1
      - colorama==0.4.6
      - colored==1.4.4
      - comm==0.1.3
      - contextlib2==21.6.0
      - contourpy==1.0.7
      - cox==0.1.post3
      - crcmod==1.7
      - cycler==0.11.0
      - Cython==0.29.35
      - debugpy==1.6.7
      - decorator==4.4.2
      - defusedxml==0.7.1
      - dill==0.3.6
      - dm-tree==0.1.8
      - dnspython==2.3.0
      - docker-pycreds==0.4.0
      - entrypoints==0.3
      - et-xmlfile==1.1.0
      - etils==1.3.0
      - exceptiongroup==1.1.1
      - executing==1.2.0
      - fasteners==0.18
      - fastjsonschema==2.17.1
      - filelock==3.12.0
      - flake8==3.7.9
      - flatbuffers==23.5.26
      - fonttools==4.39.3
      - fqdn==1.5.1
      - frozenlist==1.3.3
      - ftfy==6.1.1
      - future==0.18.3
      - fvcore @ git+https://github.com/facebookresearch/fvcore.git@fcc14bb0016408ddd818ddb0998f3df0e4e1381c
      - gast==0.4.0
      - gcs-oauth2-boto-plugin==3.0
      - gdown==4.7.1
      - geomloss==0.2.6
      - gitdb==4.0.10
      - GitPython==3.1.31
      - google==3.0.0
      - google-apitools==0.5.32
      - google-auth==2.17.1
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - google-reauth==0.1.1
      - googleapis-common-protos==1.59.0
      - GPUtil==1.4.0
      - grpcio==1.53.0
      - gsutil==5.25
      - gym==0.26.2
      - gym-notices==0.0.8
      - httplib2==0.20.4
      - huggingface-hub==0.13.3
      - humanfriendly==10.0
      - humanize==4.6.0
      - imageio-ffmpeg==0.4.8
      - imagenetv2-pytorch @ git+https://github.com/modestyachts/ImageNetV2_pytorch@9017469c74e454c444bb48d19a4aa43211cc1f3a
      - importlib-metadata==6.1.0
      - importlib-resources==5.12.0
      - install==1.3.5
      - iopath==0.1.9
      - ipywidgets==8.0.6
      - isoduration==20.11.0
      - isort==4.3.21
      - jax==0.4.11
      - jedi==0.18.2
      - jupyter==1.0.0
      - jupyter-console==6.6.3
      - jupyter-events==0.6.3
      - jupyter_client==8.2.0
      - jupyter_core==5.3.0
      - jupyter_server==2.6.0
      - jupyter_server_terminals==0.4.4
      - jupyterlab-pygments==0.2.2
      - jupyterlab-widgets==3.0.7
      - keras==2.12.0
      - kornia==0.6.11
      - lazy_loader==0.2
      - learn2learn==0.1.7
      - libclang==16.0.0
      - librosa==0.10.1
      - littleutils==0.2.2
      - Markdown==3.4.3
      - markdown-it-py==2.2.0
      - MarkupSafe==2.1.2
      - matplotlib-inline==0.1.6
      - mccabe==0.6.1
      - mdurl==0.1.2
      - mistune==2.0.5
      - ml-collections==0.1.1
      - ml-dtypes==0.2.0
      - mmcv-full==1.7.1
      - mock==5.0.2
      - model-index==0.1.11
      - monotonic==1.6
      - moviepy==1.0.3
      - mpmath==1.2.1
      - msgpack==1.0.5
      - multidict==6.0.4
      - munkres==1.1.4
      - nbclassic==1.0.0
      - nbclient==0.8.0
      - nbconvert==7.4.0
      - nbformat==5.9.0
      - nest-asyncio==1.5.6
      - networkx==3.0
      - notebook==6.5.4
      - notebook_shim==0.2.3
      - oauth2client==4.1.3
      - oauthlib==3.2.2
      - ogb==1.3.5
      - open-clip-torch==2.16.0
      - openmim==0.3.7
      - openpyxl==3.1.2
      - opt-einsum==3.3.0
      - ordered-set==4.1.0
      - outdated==0.2.2
      - overrides==7.3.1
      - parso==0.8.3
      - pathtools==0.1.2
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - platformdirs==3.5.1
      - ply==3.11
      - portalocker==2.8.0
      - POT==0.9.0
      - prettytable==3.7.0
      - proglog==0.1.10
      - prometheus-client==0.17.0
      - promise==2.3
      - prompt-toolkit==3.0.38
      - protobuf==3.20.3
      - py-cpuinfo==9.0.0
      - py3nvml==0.2.7
      - pyasn1==0.5.0rc2
      - pyasn1-modules==0.3.0rc1
      - pycocotools==2.0.6
      - pycodestyle==2.5.0
      - pyflakes==2.1.1
      - Pygments==2.15.1
      - pymongo==4.3.3
      - pyparsing==3.0.9
      - PyQt5-sip==12.11.0
      - pyrouge==0.1.3
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - pytube==15.0.0
      - pytz==2023.3
      - pyu2f==0.1.5
      - PyWavelets==1.4.1
      - qtconsole==5.4.3
      - qpth==0.0.15
      - requests-oauthlib==1.3.1
      - retry-decorator==1.1.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.3.5
      - robustness==1.2.1.post2
      - rsa==4.7.2
      - seaborn==0.12.2
      - Send2Trash==1.8.2
      - sentencepiece==0.1.97
      - sentry-sdk==1.25.0
      - setproctitle==1.3.2
      - shapely==2.0.1
      - shortuuid==1.0.11
      - slurm-gpustat==0.0.12
      - smmap==5.0.0
      - sniffio==1.3.0
      - soundfile==0.12.1
      - soupsieve==2.4
      - soxr==0.3.6
      - stack-data==0.6.2
      - submitit==1.4.5
      - tables==3.8.0
      - tabulate==0.9.0
      - tb-nightly==2.13.0a20230402
      - tensorboard==2.12.3
      - tensorboard-data-server==0.7.0
      - tensorboard-logger==0.1.0
      - tensorboard-plugin-wit==1.8.1
      - tensorboardX==2.6
      - tensorflow==2.12.0
      - tensorflow-addons==0.20.0
      - tensorflow-datasets==4.9.2
      - tensorflow-estimator==2.12.0
      - tensorflow-io-gcs-filesystem==0.32.0
      - tensorflow-metadata==1.13.1
      - termcolor==2.3.0
      - terminado==0.17.1
      - terminaltables==3.1.10
      - tfds-nightly==4.4.0.dev202201080107
      - threadpoolctl==3.1.0
      - tifffile==2023.3.21
      - timm==0.4.12
      - tinycss2==1.2.1
      - tokenizers==0.13.3
      - torchprofile==0.0.4
      - tornado==6.3.2
      - transformers==4.26.0
      - triton==2.0.0
      - typeguard==2.13.3
      - uri-template==1.2.0
      - wandb==0.13.3
      - wcwidth==0.2.6
      - webcolors==1.13
      - webdataset==0.2.48
      - webencodings==0.5.1
      - websocket-client==1.5.2
      - Werkzeug==2.2.3
      - widgetsnbextension==4.0.7
      - wilds==2.0.0
      - wrapt==1.14.1
      - xmltodict==0.13.0
      - yacs==0.1.8
      - yapf==0.29.0
      - yarl==1.9.2
      - zipp==3.15.0
