name: c2kd
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=1.1.1w=h7f8727e_0
  - pip=25.2=pyhc872135_1
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.0=h12debd9_5
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==1.4.0
      - array-record==0.8.1
      - asttokens==3.0.0
      - astunparse==1.6.3
      - attrs==25.4.0
      - beartype==0.22.2
      - blosc2==2.0.0
      - braceexpand==0.1.7
      - cachetools==6.2.1
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.0
      - cloudpickle==3.1.1
      - cmake==3.25.0
      - colored==2.3.1
      - comm==0.2.3
      - contourpy==1.3.2
      - cycler==0.12.1
      - cython==3.1.5
      - debugpy==1.8.17
      - decorator==5.2.1
      - dm-tree==0.1.9
      - docker-pycreds==0.4.0
      - einops==0.8.1
      - etils==1.13.0
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - filelock==3.20.0
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - gast==0.4.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-api-core==2.26.0
      - google-api-python-client==2.185.0
      - google-auth==2.41.1
      - google-auth-httplib2==0.2.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - googleapis-common-protos==1.71.0
      - grpcio==1.76.0
      - h5py==3.15.1
      - hf-xet==1.1.10
      - httplib2==0.31.0
      - huggingface-hub==0.35.3
      - humanfriendly==10.0
      - humanize==4.14.0
      - idna==3.11
      - imageio==2.37.0
      - importlib-resources==6.5.2
      - ipykernel==7.0.1
      - ipython==8.21.0
      - ipython-genutils==0.2.0
      - jax==0.4.30
      - jaxlib==0.4.30
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - jupyter-client==8.6.3
      - jupyter-core==5.9.1
      - keras==2.12.0
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - libclang==18.1.1
      - lit==15.0.7
      - littleutils==0.2.4
      - markdown==3.9
      - markdown-it-py==2.2.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - ml-dtypes==0.5.3
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - numexpr==2.14.1
      - numpy==1.26.0
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - oauthlib==3.3.1
      - ogb==1.3.6
      - opencv-python==4.7.0.72
      - opt-einsum==3.4.0
      - outdated==0.2.2
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - pathtools==0.1.2
      - pexpect==4.9.0
      - pillow==12.0.0
      - platformdirs==4.5.0
      - promise==2.3
      - prompt-toolkit==3.0.52
      - proto-plus==1.26.1
      - protobuf==3.20.3
      - psutil==7.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pywavelets==1.8.0
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - qtconsole==5.4.3
      - qtpy==2.3.1
      - regex==2023.3.23
      - requests==2.32.5
      - requests-oauthlib==1.3.1
      - rich==13.3.5
      - rsa==4.7.2
      - scikit-image==0.20.0
      - scikit-learn==1.7.2
      - scipy==1.10.1
      - seaborn==0.13.2
      - sentencepiece==0.1.97
      - sentry-sdk==1.25.0
      - setproctitle==1.3.2
      - shapely==2.0.1
      - shortuuid==1.0.11
      - simplejson==3.20.2
      - six==1.17.0
      - slurm-gpustat==0.0.12
      - smmap==5.0.0
      - sniffio==1.3.0
      - soundfile==0.12.1
      - soupsieve==2.4
      - soxr==0.3.6
      - stack-data==0.6.2
      - submitit==1.4.5
      - sympy==1.14.0
      - tables==3.8.0
      - tabulate==0.9.0
      - tensorboard==2.12.3
      - tensorboard-data-server==0.7.0
      - tensorboardx==2.6
      - tensorflow-addons==0.20.0
      - tensorflow-datasets==4.9.2
      - tensorflow-estimator==2.12.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-metadata==1.13.1
      - termcolor==2.3.0
      - terminado==0.17.1
      - threadpoolctl==3.6.0
      - tifffile==2023.3.21
      - timm==0.4.12
      - tokenizers==0.13.3
      - toml==0.10.2
      - torch==2.0.1+cu118
      - torchaudio==2.0.2+cu118
      - torchvision==0.15.2+cu118
      - tornado==6.3.2
      - tqdm==4.67.1
      - traitlets==5.9.0
      - transformers==4.26.0
      - triton==2.0.0
      - typeguard==2.13.3
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - uritemplate==4.2.0
      - urllib3==2.5.0
      - wandb==0.13.3
      - wcwidth==0.2.6
      - webcolors==1.13
      - webdataset==0.2.48
      - webencodings==0.5.1
      - websocket-client==1.5.2
      - werkzeug==2.2.3
      - widgetsnbextension==4.0.7
      - wilds==2.0.0
      - wrapt==1.14.1
      - xmltodict==0.13.0
      - yacs==0.1.8
      - yapf==0.29.0
      - yarl==1.9.2
      - zipp==3.23.0
prefix: /root/anaconda3/envs/c2kd
